name: modem-manager
version: 1.12.6-1-dev
summary: ModemManager is a service which controls mobile broadband
description: |
  ModemManager is a DBus-activated daemon which controls mobile broadband
  (2G/3G/4G) devices and connections. Whether built-in devices, USB dongles,
  bluetooth-paired telephones or professional RS232/USB devices with external
  power supplies, ModemManager is able to prepare and configure the modems and
  setup connections with them.
  Please find the source code at https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager/+ref/snap-1.12
confinement: strict
grade: stable
base: core20

slots:
  service: modem-manager

plugs:
  mmcli: modem-manager

hooks:
  configure:
    plugs: [mmcli]

layout:
  /usr/lib/ModemManager:
    symlink: $SNAP/usr/lib/ModemManager
  /usr/lib/libqmi/qmi-proxy:
    symlink: $SNAP/usr/lib/libqmi/qmi-proxy
  /usr/lib/libmbim/mbim-proxy:
    symlink: $SNAP/usr/lib/libmbim/mbim-proxy

apps:
  mmcli:
    command: bin/mmcli
    plugs: [mmcli]
  modemmanager:
    command: bin/modemmanager
    daemon: simple
    slots: [service]
  mbimcli:
    command: usr/bin/mbimcli
    slots: [service]
  mbim-network:
    command: usr/bin/mbim-network
    slots: [service]
  qmicli:
    command: usr/bin/qmicli
    slots: [service]
  qmi-network:
    command: usr/bin/qmi-network
    slots: [service]

parts:
  modemmanager-hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  modemmanager-bin:
    plugin: dump
    source: bin
    organize:
      modemmanager: bin/modemmanager
      mmcli: bin/mmcli
      mmcli-internal: bin/mmcli-internal

  modemmanager-data:
    plugin: dump
    source: data
    organize:
      copyright: usr/share/doc/modem-manager/copyright

  changelog:
    plugin: nil
    override-build: |
      cp "$SNAPCRAFT_PROJECT_DIR"/ChangeLog "$SNAPCRAFT_PART_INSTALL"
    organize:
      ChangeLog: usr/share/doc/modem-manager/ChangeLog

  modemmanager:
    plugin: autotools

    source: https://git.launchpad.net/ubuntu/+source/modemmanager
    source-type: git
    source-branch: applied/1.12.8-1

    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --libexecdir=/usr/lib/ModemManager
      - --sysconfdir=/etc
      - --enable-gtk-doc=no
      - --with-polkit=no
      - --enable-vala=no
      # Set explicitly CFLAGS until lp: #1791946 is solved
      - CFLAGS=-O2

    build-packages:
      - intltool
      - gtk-doc-tools
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libiw-dev
      - libglib2.0-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - libnss3-dev
      - libgnutls28-dev
      - libxml-parser-perl
      - uuid-dev
      - libsystemd-dev
      - libudev-dev
      - libgudev-1.0-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - libsoup2.4-dev
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - dbus-test-runner
      - python-dbus
      - python-gi
      - libqmi-glib-dev
      - libmbim-glib-dev

    stage-packages:
      - libqmi-glib5
      - libqmi-proxy
      - libqmi-utils
      - libmbim-glib4
      - libmbim-proxy
      - libmbim-utils
      - libgudev-1.0-0

    override-pull: |
      snapcraftctl pull
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "$SNAPCRAFT_PROJECT_DIR"/patch/*.patch

    override-build: |
      ./autogen.sh
      snapcraftctl build
      # Run all tests ModemManager ships by default
      make check
      # Strip binaries
      find ../install -executable -type f | xargs file -Ni |
          grep 'application/x-executable\|application/x-sharedlib' | cut -d: -f1 | xargs strip

    filesets:
      wanted:
        - usr/bin/mmcli
        - usr/sbin/ModemManager
        - usr/lib/ModemManager/
        - usr/lib/*/libgudev-1.0.so*
        - usr/lib/libmm-glib.so*
        - usr/share/doc/libgudev-1.0-0/copyright
        - usr/lib/*/libmbim-glib.so*
        - usr/lib/libmbim/mbim-proxy
        - usr/bin/mbimcli
        - usr/bin/mbim-network
        - usr/share/doc/libmbim-glib4/copyright
        - usr/share/doc/libmbim-proxy/copyright
        - usr/share/doc/libmbim-utils/copyright
        - usr/lib/*/libqmi-glib.so*
        - usr/lib/libqmi/qmi-proxy
        - usr/bin/qmicli
        - usr/bin/qmi-network
        - usr/share/doc/libqmi-glib5/copyright
        - usr/share/doc/libqmi-proxy/copyright
        - usr/share/doc/libqmi-utils/copyright

    prime:
      - $wanted

  # This part is to make sure we get notifications from the review tools
  modemmanager-phony:
    after: [ modemmanager, changelog, modemmanager-hooks,
             modemmanager-bin, modemmanager-data ]
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
      - python3-minimal
      - python3-yaml
    stage-packages:
      - modemmanager
    # Check versions and make sure nothing from the staged packages is installed
    override-build: |
      #./build-tools/cmp-stage-build.py modemmanager modemmanager
      rm -rf ../install/*
    # Find out packages not primed in the end, for CI consumption
    #override-prime: |
    #  mkdir -p snap
    #  "$SNAPCRAFT_PART_SRC"/build-tools/find-non-primed-pkgs.sh \
    #      "$SNAPCRAFT_PROJECT_DIR" snap/unstage.txt
