snapcraft-version: 8.2.11
snapcraft-started-at: '2024-06-18T07:00:37.290130Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '24.04'
name: modem-manager
version: 1.23.4-1
summary: ModemManager is a service which controls mobile broadband
description: |
  ModemManager is a DBus-activated daemon which controls mobile broadband
  (2G/3G/4G) devices and connections. Whether built-in devices, USB dongles,
  bluetooth-paired telephones or professional RS232/USB devices with external
  power supplies, ModemManager is able to prepare and configure the modems and
  setup connections with them.
  Please find the source code at
  https://github.com/snapcore/modem-manager-snap/tree/snap-24
base: core24
grade: stable
confinement: strict
apps:
  mmcli:
    command: bin/mmcli
    plugs:
    - mmcli
  modemmanager:
    command: bin/modemmanager
    daemon: simple
    slots:
    - service
  mbimcli:
    command: usr/bin/mbimcli
    slots:
    - service
  mbim-network:
    command: usr/bin/mbim-network
    slots:
    - service
  qmicli:
    command: usr/bin/qmicli
    slots:
    - service
  qmi-network:
    command: usr/bin/qmi-network
    slots:
    - service
parts:
  modemmanager-hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  modemmanager-bin:
    plugin: dump
    source: bin
    organize:
      modemmanager: bin/modemmanager
      mmcli: bin/mmcli
      mmcli-internal: bin/mmcli-internal
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  changelog:
    plugin: nil
    override-build: 'cp "/build/ci-modem-manager-bvjo2e3olsqei022"/ChangeLog "$CRAFT_PART_INSTALL"

      '
    organize:
      ChangeLog: snap/ChangeLog
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
    - dpkg-dev
    - git
    stage-packages:
    - libgudev-1.0-0=1:238-5ubuntu1
    - libmbim-glib4=1.31.2-0ubuntu3
    - libmbim-proxy=1.31.2-0ubuntu3
    - libmm-glib0=1.23.4-0ubuntu2
    - libqmi-glib5=1.35.2-0ubuntu2
    - libqmi-proxy=1.35.2-0ubuntu2
    - libqrtr-glib0=1.2.2-1ubuntu4
    - modemmanager=1.23.4-0ubuntu2
    override-build: |
      set -ex
      find "$CRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/modemmanager*' \
           -and -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/libmm-glib0*' \
           -delete
      find "$CRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$CRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$CRAFT_PART_INSTALL"/build-tools
    prime:
    - usr/share/doc/modemmanager
    - usr/share/doc/libmm-glib0
    stage: []
  modemmanager:
    plugin: meson
    after:
    - stack-snaps-tools
    source: https://git.launchpad.net/ubuntu/+source/modemmanager
    source-type: git
    source-branch: applied/ubuntu/noble
    meson-parameters:
    - --prefix=/usr
    - --libdir=/usr/lib
    - --libexecdir=/usr/lib/ModemManager
    - --sysconfdir=/etc
    - -Db_pie=true
    - -Dgtk_doc=false
    - -Dpolkit=no
    - -Dvapi=false
    build-environment:
    - CFLAGS: -O2 -Wl,-z,relro,-z,now
    build-packages:
    - meson
    - intltool
    - gtk-doc-tools
    - libdbus-glib-1-dev
    - libdbus-1-dev
    - libiw-dev
    - libglib2.0-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - libnl-genl-3-dev
    - libnss3-dev
    - libgnutls28-dev
    - libxml-parser-perl
    - uuid-dev
    - libsystemd-dev
    - libudev-dev
    - libgudev-1.0-dev
    - libgirepository1.0-dev
    - gobject-introspection
    - libsoup2.4-dev
    - libglib2.0-doc
    - libmm-glib-dev
    - libndp-dev
    - libreadline-dev
    - libnewt-dev
    - dbus-test-runner
    - python3-dbus
    - python3-gi
    - libqmi-glib-dev
    - libmbim-glib-dev
    stage-packages:
    - libgudev-1.0-0=1:238-5ubuntu1
    - libmbim-glib4=1.31.2-0ubuntu3
    - libmbim-proxy=1.31.2-0ubuntu3
    - libmbim-utils=1.31.2-0ubuntu3
    - libqmi-glib5=1.35.2-0ubuntu2
    - libqmi-proxy=1.35.2-0ubuntu2
    - libqmi-utils=1.35.2-0ubuntu2
    - libqrtr-glib0=1.2.2-1ubuntu4
    override-build: |
      set -ex
      cd "$CRAFT_PART_SRC"
      "/build/ci-modem-manager-bvjo2e3olsqei022/stage"/build-tools/check-versions modemmanager
      # Apply snap related patches
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "/build/ci-modem-manager-bvjo2e3olsqei022"/patch/*.patch
      cd "$CRAFT_PART_BUILD"
      craftctl default
      # Run all tests ModemManager ships by default
      ninja test
      # Strip binaries
      find "$CRAFT_PART_INSTALL"/ -executable -type f | xargs file -Ni |
          grep 'application/x-.*executable\|application/x-.*sharedlib' | cut -d: -f1 | xargs strip
    prime:
    - usr/bin/mmcli
    - usr/sbin/ModemManager
    - usr/lib/ModemManager/*so
    - usr/lib/*/libgudev-1.0.so*
    - usr/lib/libmm-glib.so*
    - usr/share/doc/libgudev-1.0-0
    - usr/lib/*/libmbim-glib.so*
    - usr/lib/*/libqrtr-glib.so*
    - usr/bin/mbimcli
    - usr/bin/mbim-network
    - usr/share/doc/libmbim-glib4
    - usr/share/doc/libmbim-proxy
    - usr/share/doc/libmbim-utils
    - usr/lib/*/libqmi-glib.so*
    - usr/bin/qmicli
    - usr/bin/qmi-firmware-update
    - usr/bin/qmi-network
    - usr/share/doc/libqmi-glib5
    - usr/share/doc/libqmi-proxy
    - usr/share/doc/libqmi-utils
    - usr/libexec/*
    stage: []
architectures:
- arm64
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/+snap/ci-modem-manager-bvjo2e3olsqei022/+build/2516836
build-packages: []
build-snaps: []
primed-stage-packages:
- libgudev-1.0-0=1:238-5ubuntu1
- libmbim-glib4=1.31.2-0ubuntu3
- libmbim-proxy=1.31.2-0ubuntu3
- libmbim-utils=1.31.2-0ubuntu3
- libmm-glib0=1.23.4-0ubuntu2
- libqmi-glib5=1.35.2-0ubuntu2
- libqmi-proxy=1.35.2-0ubuntu2
- libqmi-utils=1.35.2-0ubuntu2
- libqrtr-glib0=1.2.2-1ubuntu4
- modemmanager=1.23.4-0ubuntu2
